# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
VEOSBOX = "vEOS-lab-4.16.6"
Vagrant.configure(2) do |config|

  config.vm.define "base" do |base|
    base.vm.box = "hashicorp/precise64"
  end

  config.vm.define "spine01" do |spine01|
   spine01.vm.box = VEOSBOX
   spine01.vm.network "private_network", virtualbox__intnet: "s01l01", ip: "169.254.1.11", auto_config: false
   spine01.vm.network "private_network", virtualbox__intnet: "s01l02", ip: "169.254.1.11", auto_config: false
   spine01.vm.network "private_network", virtualbox__intnet: "s01l03", ip: "169.254.1.11", auto_config: false
   spine01.vm.network "private_network", virtualbox__intnet: "s01l04", ip: "169.254.1.11", auto_config: false
  end

  config.vm.define "spine02" do |spine02|
   spine02.vm.box = VEOSBOX
   spine02.vm.network "private_network", virtualbox__intnet: "s02l01", ip: "169.254.1.11", auto_config: false
   spine02.vm.network "private_network", virtualbox__intnet: "s02l02", ip: "169.254.1.11", auto_config: false
   spine02.vm.network "private_network", virtualbox__intnet: "s02l03", ip: "169.254.1.11", auto_config: false
   spine02.vm.network "private_network", virtualbox__intnet: "s02l04", ip: "169.254.1.11", auto_config: false
  end

  config.vm.define "leaf01" do |leaf01|
   leaf01.vm.box = VEOSBOX
   leaf01.vm.network "private_network", virtualbox__intnet: "s01l01", ip: "169.254.1.11", auto_config: false
   leaf01.vm.network "private_network", virtualbox__intnet: "s02l01", ip: "169.254.1.11", auto_config: false
   leaf01.vm.network "private_network", virtualbox__intnet: "l01h01", ip: "169.254.1.11", auto_config: false
   leaf01.vm.network "private_network", virtualbox__intnet: "l01h02", ip: "169.254.1.11", auto_config: false
  end

  config.vm.define "leaf02" do |leaf02|
   leaf02.vm.box = VEOSBOX
   leaf02.vm.network "private_network", virtualbox__intnet: "s01l02", ip: "169.254.1.11", auto_config: false
   leaf02.vm.network "private_network", virtualbox__intnet: "s02l02", ip: "169.254.1.11", auto_config: false
   leaf02.vm.network "private_network", virtualbox__intnet: "l02h01", ip: "169.254.1.11", auto_config: false
   leaf02.vm.network "private_network", virtualbox__intnet: "l02h02", ip: "169.254.1.11", auto_config: false
  end

  config.vm.define "leaf03" do |leaf03|
   leaf03.vm.box = VEOSBOX
   leaf03.vm.network "private_network", virtualbox__intnet: "s01l03", ip: "169.254.1.11", auto_config: false
   leaf03.vm.network "private_network", virtualbox__intnet: "s02l03", ip: "169.254.1.11", auto_config: false
   leaf03.vm.network "private_network", virtualbox__intnet: "l03h01", ip: "169.254.1.11", auto_config: false
   leaf03.vm.network "private_network", virtualbox__intnet: "l03h02", ip: "169.254.1.11", auto_config: false
  end

  config.vm.define "leaf04" do |leaf04|
   leaf04.vm.box = VEOSBOX
   leaf04.vm.network "private_network", virtualbox__intnet: "s01l04", ip: "169.254.1.11", auto_config: false
   leaf04.vm.network "private_network", virtualbox__intnet: "s02l04", ip: "169.254.1.11", auto_config: false
   leaf04.vm.network "private_network", virtualbox__intnet: "l04h01", ip: "169.254.1.11", auto_config: false
   leaf04.vm.network "private_network", virtualbox__intnet: "l04h02", ip: "169.254.1.11", auto_config: false
  end
end

# Create Ethernet1
#config.vm.network "private_network", virtualbox_inet: true, ip: "169.254.1.11", auto_config: false
# Create Ethernet2
#config.vm.network "private_network", virtualbox_inet: true, ip: "169.254.1.12", auto_config: false
# Create Ethernet3
#config.vm.network "private_network", virtualbox_inet: true, ip: "169.254.1.13", auto_config: false
# Create Ethernet4
#config.vm.network "private_network", virtualbox_inet: true, ip: "169.254.1.14", auto_config: false
